# This base image can be found in 'Dockerfile'
image: $TEST_IMAGE

stages:
  - build-env
  - build
  - test

variables:
  TEST_IMAGE: ${CI_REGISTRY_IMAGE}/test

build-image:
  stage: build-env
  when: manual
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.16.0
    entrypoint: [""]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - mkdir docker
    - cp Dockerfile docker/
    - cp environment.yml docker/
    - cp package.json docker/
    - /kaniko/executor
      --context $CI_PROJECT_DIR/docker
      --dockerfile $CI_PROJECT_DIR/docker/Dockerfile
      --destination $TEST_IMAGE
      --cache=true

build:
  image: $TEST_IMAGE
  stage: build
  script:
    - python3 -m compileall zesje
    - yarn build
  artifacts:
    paths:
      - zesje/static
    expire_in: 1 week

.conda-env: &conda-env
  before_script:
    - source activate zesje-dev

test_js:
  <<: *conda-env
  image: $TEST_IMAGE
  stage: test
  script: 
    - yarn test:js

lint_js:
  <<: *conda-env
  image: $TEST_IMAGE
  stage: test
  allow_failure: true
  script:
    - yarn lint:js

lint_py:
  <<: *conda-env
  image: $TEST_IMAGE
  stage: test
  allow_failure: true
  script:
    - yarn lint:py

test_py:
  <<: *conda-env
  image: $TEST_IMAGE
  stage: test
  script:
    - yarn test:py:cov
  artifacts:
    paths:
      - cov.html/
    expire_in: 1 week
