
# This base image can be found in 'Dockerfile'
image: zesje/base

stages:
  - lint
  - test

# Special hidden job that is merged with JS jobs
.node_modules: &node_modules
  # Cache the JS modules that yarn fetches
  cache:
    untracked: true
    key: "$CI_COMMIT_SHA"
    paths:
      - node_modules/
  before_script:
  - yarn install

lint_js:
  <<: *node_modules
  stage: lint
  allow_failure: true
  script:
    - yarn build
    - yarn lint:js

lint_py:
  stage: lint
  allow_failure: true
  script: 
    - python -m compileall zesje
    - yarn lint:py

test_js:
  <<: *node_modules
  stage: test
  script: yarn test:js

test_py:
  stage: test
  script: yarn test:py