# This base image can be found in 'Dockerfile'
image: zesje/base

stages:
  - build
  - test

# Special hidden job that is merged with JS jobs
.node_modules: &node_modules
  # Cache the JS modules that yarn fetches
  cache:
    untracked: true
    paths:
      - .yarn-cache
  before_script:
    - yarn install --cache-folder .yarn-cache

.python_packages: &python_packages
  before_script:
    - pip install --no-cache-dir -r requirements.txt -r requirements-dev.txt

build:
  <<: *node_modules
  stage: build
  script:
    - python3 -m compileall zesje
    - yarn build
  artifacts:
    paths:
      - zesje/static
    expire_in: 1 week

test_js:
  <<: *node_modules
  stage: test
  script: yarn test:js

test_py:
  <<: *python_packages
  stage: test
  script: yarn test:py

lint_js:
  <<: *node_modules
  stage: test
  allow_failure: true
  script:
    - yarn lint:js

lint_py:
  <<: *python_packages
  stage: test
  allow_failure: true
  script:
    - yarn lint:py
    
cov:
  <<: *python_packages
  stage: test
  script:
    - python -m pytest --cov=zesje
  artifacts:
    paths:
      - cov.xml
    expire_in: 1 week
