
# This base image can be found in 'Dockerfile'
image: zesje/base

# Cache the JS modules that yarn fetches
cache:
  untracked: true
  key: "$CI_COMMIT_SHA"
  paths:
    - node_modules/

stages:
  - lint
  - test

lint_js:
  stage: lint
  before_script:
  - yarn install
  allow_failure: true
  script:
    - yarn build
    - yarn lint:js

lint_py:
  stage: lint
  allow_failure: true
  script: 
    - python -m compileall zesje
    - yarn lint:py

test_js:
  stage: test
  before_script:
  - yarn install
  script: yarn test:js

test_py:
  stage: test
  script: yarn test:py