
# This base image can be found in 'Dockerfile'
image: zesje/base

# Cache the JS modules that yarn fetches
cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

stages:
  - install
  - build
  - lint
  - test

setup:
  stage: setup
  script:
    - yarn install

build_js:
  stage: build
  script:
    - yarn build

build_py:
  stage: build
  script: python -m compileall zesje

lint_js:
  stage: lint
  script: yarn lint:js

lint_py:
  stage: lint
  script: yarn lint:py

test_js:
  stage: test
  script: yarn test:js

test_py:
  stage: test
  script: yarn test:py