# This base image can be found in 'Dockerfile'
image: $TEST_IMAGE

stages:
  - build-env
  - build
  - test

variables:
  TEST_IMAGE: ${CI_REGISTRY_IMAGE}/test

build-image:
  stage: build-env
  when: manual
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.19.0
    entrypoint: [""]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - mkdir docker
    - cp test.Dockerfile docker/
    - cp environment.yml docker/
    - cp package.json docker/
    - /kaniko/executor
      --context $CI_PROJECT_DIR/docker
      --dockerfile $CI_PROJECT_DIR/docker/test.Dockerfile
      --destination $TEST_IMAGE
      --cache=true

.conda-env: &conda-env
  before_script:
    - source activate zesje-dev
    - ln -s /yarn/* ./
    - if [[ $CI_JOB_NAME != *"py"* ]]; then yarn install; fi

build:
  <<: *conda-env
  stage: build
  script:
    - python3 -m compileall zesje
    - yarn build
  artifacts:
    paths:
      - zesje/static
    expire_in: 1 week

# test_js:
#   <<: *conda-env
#   stage: test
#   script:
#     - yarn test:js
#   artifacts:
#     reports:
#       junit: junit.xml

lint_js:
  <<: *conda-env
  stage: test
  allow_failure: true
  script:
    - yarn lint:js

lint_py:
  <<: *conda-env
  stage: test
  allow_failure: true
  script:
    - yarn lint:py

test_py:
  <<: *conda-env
  stage: test
  services:
    - mysql:8.0
  variables:
    MYSQL_DATABASE: "course_test"
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  script:
    - echo -e "\nMYSQL_HOST = 'mysql'\nMYSQL_USER = 'root'\nMYSQL_PASSWORD = None" >> zesje_test_cfg.py
    - yarn test:py:cov
  artifacts:
    paths:
      - cov.html/
    reports:
      cobertura: cov.xml
      junit: tests.xml
    expire_in: 1 week

include:
  template: Jobs/SAST.gitlab-ci.yml
