# This base image can be found in 'Dockerfile'
image: gitlab.kwant-project.org:5005/zesje/zesje/conda:latest

stages:
  - build
  - test

# Special hidden job that is merged with JS jobs
.node_modules: &node_modules
  # Cache the JS modules that yarn fetches
  cache:
    untracked: true
    paths:
      - .yarn-cache
  before_script:
    - yarn install --cache-folder .yarn-cache

.python_packages: &python_packages
  before_script:
    - conda env update

build:
  <<: *node_modules
  stage: build
  script:
    - python3 -m compileall zesje
    - yarn build
  artifacts:
    paths:
      - zesje/static
    expire_in: 1 week

test_js:
  <<: *node_modules
  stage: test
  script: yarn test:js

lint_js:
  <<: *node_modules
  stage: test
  allow_failure: true
  script:
    - yarn lint:js

lint_py:
  <<: *python_packages
  stage: test
  allow_failure: true
  script:
    - yarn lint:py

test_py:
  <<: *python_packages
  stage: test
  script:
    - yarn test:py:cov
  artifacts:
    paths:
      - cov.html/
    expire_in: 1 week
