name: zesje-dev
channels:
    - conda-forge
dependencies:
    - python=3.8
    - yarn
    - gunicorn
    - redis
    - pip
    - imagemagick
    - mysql=8.0
    - pymysql

    # Exporting
    - pandas
    - openpyxl  # required for writing dataframes as Excel spreadsheets

    # General utilities
    - numpy

    # PDF generation
    - pillow>=8.2.0  # also scan processing

    #
    # Development dependencies
    #

    # Sandbox data generation
    - lorem # For random text

    # Tests
    - pytest
    - pytest-cov
    - requests-mock

    # Linting
    - flake8

    - pip:
        # Core components
        # See https://gitlab.kwant-project.org/zesje/zesje/-/issues/660
        - werkzeug<2.1.0
        - flask>=2.0.1,<2.1.0
        - flask-restful>=0.3.9
        - flask-sqlalchemy>=2.5.1,<3.0.0
        - flask-migrate>=3.0.0,<4.0.0
        - sqlalchemy>=1.4.13,<2.0.0
        - alembic>=1.6.4,<2.0.0
        - pyyaml
        - celery>=5.1.0,<6.0.0
        - redis>=3.5.3

        #oauth library
        - requests-oauthlib>=1.3.0,<2.0.0

        #flask session management
        - flask-login
        - flask-session

        #flask role management
        - flask-principal

        # PDF generation
        - pdfrw>=0.4
        - reportlab>=3.5.0
        - wand>=0.6.6
        - zipstream-new>=1.1.8

        # Scan processing
        - opencv-python-headless>=4.5
        - pikepdf>=2.12.1
        - pylibdmtx>=0.1.9
        - pdfminer.six>=20201018

        # mysql
        - cryptography

        #
        # Development dependencies
        #

        # Sandbox data generation
        - names # For random names

        # Tests
        - git+https://github.com/jterrace/pyssim.git
        - smtpdfix  # mock email server
