name: zesje-dev
channels:
    - conda-forge
    - anaconda
dependencies:
    - python=3.8
    - yarn
    - gunicorn
    - redis
    - pip
    - imagemagick
    - mysql=5.7.20
    - pymysql

    - pip:
        # Core components
        - flask>=2.0.1,<3.0.0
        - flask-restful>=0.3.9
        - flask-sqlalchemy>=2.5.1,<3.0.0
        - flask-migrate>=3.0.0,<4.0.0
        - sqlalchemy>=1.4.13,<2.0.0
        - alembic>=1.6.4,<2.0.0
        - pyyaml
        - celery>=5.1.0,<6.0.0
        - redis>=3.5.3

        #oauth library
        - requests-oauthlib>=1.3.0,<2.0.0

        #flask session management
        - flask-login

        #flask role management
        - flask-principal

        # General utilities
        - numpy
        - scipy

        # PDF generation
        - pdfrw>=0.4
        - reportlab>=3.5.0
        - wand>=0.6.6
        - pillow>=8.2.0  # also scan processing
        - zipstream-new>=1.1.8

        # Scan processing
        - opencv-python>=4.5
        - pikepdf>=2.12.1
        - pylibdmtx>=0.1.9

        # Exporting
        - pandas
        - openpyxl  # required for writing dataframes as Excel spreadsheets

        #
        # Development dependencies
        #

        # Sandbox data generation
        - lorem # For random text
        - names # For random names

        # Tests
        - pytest
        - pyssim
        - pytest-cov
        - requests-mock

        # Linting
        - flake8
