name: zesje-dev
channels:
    - conda-forge
    - anaconda
dependencies:
    - python=3.6
    - yarn
    - gunicorn
    - redis
    - pip
    - imagemagick
    - mysql
    - pymysql

    - pip:
        # Core components
        - flask
        - flask_restful
        - flask_sqlalchemy
        - sqlalchemy
        - Flask-Migrate
        - alembic
        - pyyaml
        - celery
        - redis

        #oauth library
        - requests_oauthlib

        #flask session management
        - flask_login

        # General utilities
        - numpy==1.15.4
        - scipy==1.3.0

        # PDF generation
        - pdfrw
        - reportlab
        - Wand
        - Pillow  # also scan processing
        - zipstream-new

        # Sandbox data generation
        - lorem # For random text
        - names # For random names

        # Scan processing
        - opencv-python
        - pikepdf
        - pylibdmtx
        - pdfminer3

        # Exporting
        - pandas
        - openpyxl  # required for writing dataframes as Excel spreadsheets

        #
        # Development dependencies
        #

        # Tests
        - pytest
        - pyssim
        - pytest-cov
        - requests-mock

        # Linting
        - flake8
