""" empty message

Revision ID: 0a9fed7804cd
Revises: dccc66cf2881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a9fed7804cd'
down_revision = 'dccc66cf2881'
branch_labels = None
depends_on = None


def upgrade():
    # If you make any changes to the Exam table, please use
    # a batch operation and supply the sqlite_autoincrement
    # argument to preserve the AUTOINCREMENT keyword.
    # See ./6b926be35894_exam_autoincrement.py for a reference.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'feedback_option', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_option', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
