""" empty message

Revision ID: 31224fbb20ca
Revises: 4204f4a83863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31224fbb20ca'
down_revision = '4204f4a83863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mc_option',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('x', sa.Integer(), nullable=False),
                    sa.Column('y', sa.Integer(), nullable=False),
                    sa.Column('page', sa.Integer(), nullable=False),
                    sa.Column('label', sa.String(), nullable=False),
                    sa.Column('problem_id', sa.Integer(), nullable=True),
                    sa.Column('feedback_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['feedback_id'], ['feedback_option.id'], ),
                    sa.ForeignKeyConstraint(['problem_id'], ['solution.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
                    sa.Column('name', sa.NullType(), nullable=True),
                    sa.Column('seq', sa.NullType(), nullable=True)
                    )
    op.drop_table('mc_option')
    # ### end Alembic commands ###
