""" Add type column to Exam table

Revision ID: 4782ab8ca824
Revises: c61a8d939466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4782ab8ca824'
down_revision = 'c61a8d939466'
branch_labels = None
depends_on = None


def upgrade():
    # If you make any changes to the Exam table, please use
    # a batch operation and supply the sqlite_autoincrement
    # argument to preserve the AUTOINCREMENT keyword.
    # See ./6b926be35894_exam_autoincrement.py for a reference.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
