""" empty message

Revision ID: 4a27f48d80d8
Revises: 4204f4a83863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a27f48d80d8'
down_revision = '4204f4a83863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mc_option',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('label', sa.String(), nullable=True),
                    sa.Column('mc_type', sa.String(length=20), nullable=True),
                    sa.Column('problem_id', sa.Integer(), nullable=False),
                    sa.Column('feedback_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['feedback_id'], ['feedback_option.id'], ),
                    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
                    sa.ForeignKeyConstraint(['problem_id'], ['solution.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mc_option')
    # ### end Alembic commands ###
