""" Added a column oauth_id to store unique ids of oauth providers

Revision ID: b9aa37c392cb
Revises: ef470a16399e

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9aa37c392cb'
down_revision = 'ef470a16399e'
branch_labels = None
depends_on = None


def upgrade():
    # If you make any changes to the Exam table, please use
    # a batch operation and supply the sqlite_autoincrement
    # argument to preserve the AUTOINCREMENT keyword.
    # See ./6b926be35894_exam_autoincrement.py for a reference.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grader', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_id', sa.String(length=100), nullable=True))
        batch_op.alter_column('name',
                              existing_type=mysql.VARCHAR(length=100),
                              nullable=True)
        batch_op.drop_index('name')
        batch_op.create_unique_constraint(None, ['oauth_id'])

    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.alter_column('copy_id',
                              existing_type=mysql.INTEGER(display_width=11),
                              nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.alter_column('copy_id',
                              existing_type=mysql.INTEGER(display_width=11),
                              nullable=True)

    with op.batch_alter_table('grader', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('name', ['name'], unique=True)
        batch_op.alter_column('name',
                              existing_type=mysql.VARCHAR(length=100),
                              nullable=False)
        batch_op.drop_column('oauth_id')

    # ### end Alembic commands ###
