""" Adds support for Parent-children relationships

Revision ID: bc3cf1e01b97
Revises: 6aaff20fb6c8

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc3cf1e01b97'
down_revision = '6aaff20fb6c8'
branch_labels = None
depends_on = None


def upgrade():
    # If you make any changes to the Exam table, please use
    # a batch operation and supply the sqlite_autoincrement
    # argument to preserve the AUTOINCREMENT keyword.
    # See ./6b926be35894_exam_autoincrement.py for a reference.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'feedback_option', ['parent'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_option', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent')

    # ### end Alembic commands ###
